-- Seeding now uses Supabase Auth, so users cannot be inserted directly with SQL.
-- After running the migrations, run:
--     python -m flask --app run.py seed-db
--
-- The Flask seed command creates confirmed Supabase Auth users, links them to
-- public.users.auth_user_id, and then inserts the sample books.
