create table if not exists users (
    id integer generated by default as identity primary key,
    username varchar(50) not null unique,
    password_hash varchar(255) not null,
    role varchar(20) not null default 'regular',
    created_at timestamptz not null default now(),
    constraint check_user_role check (role in ('regular', 'admin'))
);

create table if not exists books (
    id integer generated by default as identity primary key,
    title varchar(200) not null,
    author varchar(100) not null,
    publication_year integer not null,
    isbn varchar(20) not null unique,
    amazon_url varchar(500),
    status varchar(20) not null default 'available',
    created_by_id integer references users(id) on delete set null,
    checked_out_by_id integer references users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint check_publication_year_range check (publication_year >= 1600 and publication_year <= 2030),
    constraint check_book_status check (status in ('available', 'checked_out'))
);

create table if not exists loans (
    id integer generated by default as identity primary key,
    book_id integer not null references books(id) on delete cascade,
    user_id integer references users(id) on delete set null,
    checked_out_at timestamptz not null default now(),
    returned_at timestamptz,
    actioned_by_id integer references users(id) on delete set null,
    constraint check_loan_return_after_checkout check (returned_at is null or returned_at >= checked_out_at)
);

create index if not exists ix_users_username on users(username);
create index if not exists ix_books_isbn on books(isbn);
create index if not exists ix_loans_book_id on loans(book_id);
create index if not exists ix_loans_user_id on loans(user_id);
create index if not exists ix_loans_active_book on loans(book_id) where returned_at is null;

grant usage on schema public to service_role;
grant select, insert, update, delete on table users to service_role;
grant select, insert, update, delete on table books to service_role;
grant select, insert, update, delete on table loans to service_role;
grant usage, select on all sequences in schema public to service_role;
