create table if not exists public.audit_events (
    id integer generated by default as identity primary key,
    event_type varchar(80) not null,
    actor_user_id integer references public.users(id) on delete set null,
    target_type varchar(50),
    target_id integer,
    details jsonb not null default '{}'::jsonb,
    ip_address inet,
    user_agent text,
    created_at timestamptz not null default now()
);

create index if not exists ix_audit_events_event_type on public.audit_events(event_type);
create index if not exists ix_audit_events_actor_user_id on public.audit_events(actor_user_id);
create index if not exists ix_audit_events_target on public.audit_events(target_type, target_id);
create index if not exists ix_audit_events_created_at on public.audit_events(created_at desc);

grant select, insert on table public.audit_events to service_role;
grant usage, select on all sequences in schema public to service_role;

alter table public.audit_events enable row level security;

drop policy if exists audit_events_admin_select on public.audit_events;

create policy audit_events_admin_select
on public.audit_events
for select
to authenticated
using (public.current_app_user_is_admin());